kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: foobar 
  name: kubeinvaders-role 
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
